version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=!QAZ2wsx

  blessings.order.api:
    image: ${DOCKER_REGISTRY-}blessingsorderapi
    build:
      context: .
      dockerfile: Services/Order/Blessings.OrdersApi/Dockerfile

  blessings.jeweller.api:
    image: ${DOCKER_REGISTRY-}blessingsjewellerapi
    build:
      context: .
      dockerfile: Services/Jeweller/Blessings.JewellerApi/Dockerfile


  blessings.user.api:
    image: ${DOCKER_REGISTRY-}blessingsuserapi
    build:
      context: .
      dockerfile: Services/User/Blessings.User.Api/Dockerfile

volumes:
    db:
       driver: local